### ISSUE TITLE
bruh

### ISSUE THREAD

**Issue by dimdenGD** [recapitalverb/jCMDgo#2]
DUDE GET HALP UR DOING DIS GAE BOT EVERYDAY FOR 2498429248984 YEARS AAAAAAAAAAAAAAAAAA

**Comment by recapitalverb** [comment]
Sure, mister "I created a bot with an unprotected JavaScript `eval` that let someone slam my `pm2` process just by putting in some obfuscated code".

**Comment by recapitalverb** [comment]
Unlocking for open discussion, but this issue is staying closed as it is considered as spam.

**Comment by dimdenGD** [comment]
> Sure, mister "I created a bot with an unprotected JavaScript eval that let someone slam my pm2 process just by putting in some obfuscated code".

not created but added feature to bot, and it was actually quite fun and this feature was removed just after that

**Comment by recapitalverb** [comment]
And?

**Comment by recapitalverb** [comment]
> not created but added feature to bot

"I didn't breathe but I took in air by depressurising the lungs and letting air rush in for the purpose of supplying blood with fresh oxygen"

> this feature was removed just after that

Yeah, except that wasn't what that actually happened. You took the uneducated, lazy path of simply blacklisting me from the bot after I penetrated through the JavaScript "sandbox" (as in using a random safe-eval lib plus some blindly thrown together blacklist you practically duct-taped on top) and killed your `pm2` process **several** times, AFTER I warned you again and again and AGAIN.

You didn't listen, you kept saying "it's fine", and when your decisions bite you back, you get butthurt and hold your grudge for **months** before creating this issue.

**Comment by dimdenGD** [comment]
uhhh, weird flex but ok
i forgot about this accident on next day and I literally don't care that u killed my pm2 process, i just randomly remembered how you were being ass with jcmd and that you were obsessed with it and just checked github and AFTER SO MANY MONTHS YOU'RE STILL CODING IT ALMOST EVERYDAY

**Comment by recapitalverb** [comment]
> uhhh, weird flex but ok

Welcome to GitHub.

> i just randomly remembered how you were being ass with jcmd and that you were obsessed with it and just checked github

I'm not sure one should spontaneously open a spam issue just because they "randomly remembered" something about the project.

> AFTER SO MANY MONTHS YOU'RE STILL CODING IT ALMOST EVERYDAY

This project is more important than you may think. It is, at the time of writing:
- a useful tool many people rely on to keep their Discord servers under control, including myself. This means I have the responsibility to keep the bot running & actively finding and fixing issues. Not just for weeks, not just for months, but years. jCMD has only been around for a year - compare that to [FredBoat](https://github.com/Frederikam/FredBoat) or any other bot, tbh.
- a means for me to learn programming and, in some cases, to build useful open source projects for other Discord bot developers. Take [Tranquility](https://github.com/recapitalverb/tranquility) as an example. In fact, I'm planning on rewriting this entire bot in [Crystal](crystal-lang.org) for the sake of stability, performance and maintainability.
- something I can refer to and learn from when making other Discord bots. You heard that right, I run more bots than just jCMD. Surprised?
- a way to socialise with other people I know. I'm not sure if I should even explain this, it's pretty obvious for people who has written a bot of any kind, whether it be inside or outside of Discord.

**Comment by dimdenGD** [comment]
Sorry for disturbance.
